load_path: "" # only used when separately evaluating a pretrained model
eval: false
batch_size: 64
num_workers: 4
n_eval: 1
eval_every: 5
max_steps: 2000
use_mp: true
num_procs: 20
save_sim_states: false
